Incremented version to 1.3.5
opensearch-project/security-dashboards-plugin pull request #1071
Opened 2022-08-15 18:57 UTC by RyanL1997

Signed-off-by: Liang <jiallian@bcd0741339a1.ant.amazon.com>

### Description
Increment version to 1.3.5

### Category
Maintenance

### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/2348

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-08-16 18:48 UTC, peternied requested changes
Please update the sign off on the commit to your GitHub associated email address

2022-08-17 13:53 UTC, cwperks approved these changes

2022-08-17 14:15 UTC, RyanL1997 commented
Hi @peternied, thx for your review. I've changed the signoff in both commit and comment, and CI is passing now.

2022-08-17 16:57 UTC, peternied approved these changes

2022-08-17 16:57 UTC, merged