[Backport 1.1] Tenancy getting Lost in SAML Authentication
opensearch-project/security-dashboards-plugin pull request #1126
Opened 2022-10-05 14:57 UTC by anijain-Amazon

### Description
This fix is for ensuring that tenancy information is read from the local storage in SAML Authentication workflow after a user log out of OS Dashboard. 

### Category
Bug Fix

### Why these changes are required?
To have a good user experience and ensure their tenancy is reloaded after logging in into a new session in the same browser. 

### What is the old behavior before changes and new behavior after changes?
Tenancy information was not being read from local storage after logout in old behaviour for SAML authentication enabled domains. After the changes, tenancy information will be read from local storage. This is ensured as the session storage variable `pendistro::security::tenant::show_popup` is set to null after logout in SAML Authentication workflow. 

### Issues Resolved
[Issue](https://github.com/opensearch-project/security-dashboards-plugin/issues/1057) created for this bug

### Testing
The changes have been made in security-dashboards-plugin and the same has been tested for OS Dashboards in SAML authentication enabled domains. 

https://user-images.githubusercontent.com/110471048/183618009-30728f98-f108-490f-9516-d93ecd545f38.mp4

### Check List
- [x] New functionality includes testing
- [x] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-10-05 15:36 UTC, DarshitChanpura approved these changes

2022-10-05 18:00 UTC, peternied commented
We will not be releasing 1.1, only versions 1.3, so this backport won't accomplish anything.  Closing this pull request out.

2022-10-06 04:09 UTC, anijain-Amazon commented
We have to pull the changes on Managed Services end. We can only do so if the changes are merged to the versions branch. 

@peternied Reopen the PR again and merge the same.

2022-10-06 15:42 UTC, peternied requested changes
@cwperks I think there was a conversation that happen offline that would be good to include here, can you reference that before this change is merged?

2022-10-07 03:16 UTC, anijain-Amazon commented
@peternied This has been included in the [PR](https://github.com/opensearch-project/project-website/pull/1062/files) for release page.

2022-10-07 03:49 UTC, peternied approved these changes

2022-10-07 03:49 UTC, merged