Fix CVE dependencies
opensearch-project/security-dashboards-plugin pull request #1308
Opened 2023-01-25 21:42 UTC by RyanL1997

Signed-off-by: Ryan Liang <jiallian@amazon.com>

### Description
[Describe what this change achieves]

### Category
Maintenance

### Why these changes are required?

### What is the old behavior before changes and new behavior after changes?

### Issues Resolved
[List any issues this PR will resolve (Is this a backport? If so, please add backport PR # and/or commits #)]

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-01-25 23:34 UTC, peternied reviewed
Please update the pull request description with more details about this change.

Mend isn't reporting [link](https://github.com/opensearch-project/security-dashboards-plugin/pull/1308/checks?check_run_id=10889052935) any issues have been fixed, how do we know these changes are correct?

2023-01-25 23:36 UTC, peternied commented
Please include the CVE referenced in the change like was done here, https://github.com/opensearch-project/security/pull/2350 

Multiple entries, one on each line is a good way to do this.

2023-01-26 15:26 UTC, DarshitChanpura requested changes
Why delete yarn.lock? If needed you can push updated yarn.lock
Also, can you add a brief description of why this change is required or point to the issue that requires this change?

2023-01-26 15:34 UTC, cwperks commented
@DarshitChanpura This does not delete the yarn.lock, there are just a lot of lines deleted. I believe a lot of these dependencies were coming from storybook from OSD core which was deleted so there were a lot of deletions in this yarn.lock as well.

For some additional context, `main` does not have a `yarn.lock`, but 1.3 does. The reason for that is because of the backport of the SAML integration tests which needed to lock in a version of selenium that was compatible with node 10.24.1.

2023-01-26 16:01 UTC, DarshitChanpura commented
> @DarshitChanpura This does not delete the yarn.lock, there are just a lot of lines deleted. I believe a lot of these dependencies were coming from storybook from OSD core which was deleted so there were a lot of deletions in this yarn.lock as well.
Yep I saw 4/5 red bars on yarn.lock and concluded it was deleted 🤦 .

> For some additional context, `main` does not have a `yarn.lock`, but 1.3 does. The reason for that is because of the backport of the SAML integration tests which needed to lock in a version of selenium that was compatible with node 10.24.1.
Yep, it was introduced with that PR and that is why I was trying to make sure it wasn't deleted.

2023-01-26 17:46 UTC, RyanL1997 commented
@peternied @DarshitChanpura Thanks for the review, and I just attach the dependencies names and version number with the issue links.

2023-01-26 19:46 UTC, cwperks commented
@RyanL1997 Can you rebase this with the latest from 1.3? The version increment was just merged.

2023-01-26 21:01 UTC, cwperks approved these changes

2023-01-26 21:44 UTC, DarshitChanpura approved these changes

2023-01-26 21:45 UTC, merged

2023-01-26 21:49 UTC, RyanL1997 commented
Update: I also run the sanity tests with this changes and it is all good.