Increment version to 1.3.9
opensearch-project/security-dashboards-plugin pull request #1315
Opened 2023-02-04 01:09 UTC by Divyaasm

Signed-off-by: Divya Madala <divyaasm@amazon.com>

Bumped version from 1.3.8 to 1.3.9

Bump version in  integrationtest.yml before merging the issue.

### Category
[Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation]

### Why these changes are required?

### What is the old behavior before changes and new behavior after changes?

### Issues Resolved
[List any issues this PR will resolve (Is this a backport? If so, please add backport PR # and/or commits #)]

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-02-06 14:16 UTC, scrawfor99 approved these changes

2023-02-06 17:36 UTC, RyanL1997 approved these changes

2023-02-06 19:33 UTC, DarshitChanpura requested changes
[integration-test.yml](https://github.com/opensearch-project/security-dashboards-plugin/blob/1.3/.github/workflows/integration-test.yml) needs to updated before merging

2023-02-10 23:12 UTC, RyanL1997 commented
Closing this on behalf of the creation of: #1322

2023-02-10 23:12 UTC, closed without merging