feat: http proxy support for oidc
opensearch-project/security-dashboards-plugin pull request #2024
Opened 2024-07-09 12:17 UTC by Manuelraa

### Description
Add http proxy support for oidc

### Category
Enhancement

### Why these changes are required?
Users of OpenSearch Dashboards in Companies which require use of http proxy struggle to implement OIDC.

### What is the old behavior before changes and new behavior after changes?
ODIC http requests now support proxies.

### Issues Resolved
Resolves: #911

### Testing
Starting OpenSearch and OpenSearch Dashboards locally. Configure OIDC and set `https_proxy` variable. Then validate that requests are sent to proxy.

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-07-14 08:52 UTC, Manuelraa commented on server/auth/types/openid/openid_auth.ts
> +      });
> Why are we setting rejectUnauthorized to false regardless of whether https_options are present. Previous implementation only set the value when http options were present.

The `wreck.defaults()` create the following agents.
https://github.com/hapijs/wreck/blob/ba28b0420d6b0998cd8e61be7f3f8822129c88fe/lib/index.js#L36-L40
```javascript

        this.agents = this._defaults.agents || {
            https: new Https.Agent({ maxSockets: Infinity }),
            http: new Http.Agent({ maxSockets: Infinity }),
            httpsAllowUnauthorized: new Https.Agent({ maxSockets: Infinity, rejectUnauthorized: false })
        };
```

So in the previous implementation `rejectUnauthorized: false` was set even if `this.wreckHttpsOption` was empty.
Therefore my code does not change this behavior. Instead it preserves it.

2024-07-16 14:46 UTC, cwperks commented
@Manuelraa Can you change the base branch of this PR to `main`? After merge into main it can be backports to the 2.x release branch through a label.

2024-07-16 14:47 UTC, cwperks commented
The changes in this PR look ok to me. Wdyt about filing an issue about adding a functional test that covers a setup with an OIDC IdP behind a proxy?

2024-07-16 18:02 UTC, DarshitChanpura requested changes
+1 to @cwperks comment. Let's rebase this main and then backport it using backport 2.x label.

2024-07-18 07:50 UTC, Manuelraa commented
> The changes in this PR look ok to me. Wdyt about filing an issue about adding a functional test that covers a setup with an OIDC IdP behind a proxy?

Sure #2043 created

2024-07-18 08:14 UTC, Manuelraa commented
> +1 to @cwperks comment. Let's rebase this main and then backport it using backport 2.x label.

Rebased to `main`. Could you add the required label please?

2024-07-18 16:50 UTC, DarshitChanpura approved these changes
lgtm! Thanks @Manuelraa

2024-07-18 19:06 UTC, cwperks approved these changes

2024-07-18 19:08 UTC, merged