Add security permissions for Kibana Notebooks
opensearch-project/security-dashboards-plugin pull request #652
Opened 2020-12-18 01:08 UTC by joshuali925

*Issue #, if available:*

*Description of changes:*
Add Kibana Notebooks permissions to `CLUSTER_PERMISSIONS`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-06-24 09:06 UTC, sandeshkr419 requested changes
Ordering of added permissions.

2021-06-24 09:06 UTC, sandeshkr419 commented on public/apps/configuration/constants.tsx
> +  'cluster:admin/opendistro/notebooks/delete',
Arrangement of all the added permissions should be in alphabetical order to maintain consistency.

2022-01-07 23:31 UTC, davidlago commented
@joshuali925 apologies for the delay here. Could you please provide more details as to why this change is needed, and if it is related to a change/feature in a different repository a link to it as well?

If this is still needed (it was created over a year ago, sorry!) please rebase from `main` and resubmit.

2022-01-08 00:05 UTC, joshuali925 commented
> @joshuali925 apologies for the delay here. Could you please provide more details as to why this change is needed, and if it is related to a change/feature in a different repository a link to it as well?
> 
> If this is still needed (it was created over a year ago, sorry!) please rebase from `main` and resubmit.

@davidlago no worries. I thought this was merged long time ago, but we didn't see any issue in notebooks permissions i guess because [PR to backend](https://github.com/opensearch-project/security/pull/903) was merged. 

This PR was to add permissions for [notebooks plugin](https://github.com/opensearch-project/dashboards-notebooks) and is no longer relevant. The notebooks plugin is deprecated to the observability plugin (security PR #851). Closing this, thanks.

2022-01-08 00:05 UTC, closed without merging