Disable private tenant for read only users
opensearch-project/security-dashboards-plugin pull request #844
Opened 2021-10-25 20:03 UTC by giocollina

Signed-off-by: David Bennett <david.bennett@eliatra.com>

##  opensearch-project/security-dashboards-plugin pull request intake form

1. __Category:__ (_Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation_)
 
Bug fix 
 
 2. __Github Issue # or road-map entry, if available:__

https://github.com/opensearch-project/security-dashboards-plugin/issues/812

 3. __Description of changes:__

If a user has a role that is configured as "read only" in opensearch_dashboards.yml, or if a user has the default read only role "kibana_read_only", make Dashboards behave as if the private tenant is disabled. You cannot choose "Private" in the tenant switch panel anymore, and a descriptive text is displayed in the tenant switch panel.

 4. __Why these changes are required?__ 

If a user has a read only role, offering the possibility to use the private tenant does not make much sense. The read only role implies that only read operations are allowed. Since no one other as the current user is able to access the private tenant, but due to read only the current user is also not allowed to make any changes, selecting the private tenant in this situation is useless.

 5. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screen-shot if available_)

If a user has a read only role, the tenant switch panel would still allow to choose the private tenant. 

 6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration testing and manual testing_)
 
 Added additional tests to password-reset-panel.test.tsx. Manual testing for different combinations of roles and read only  roles.
 
 7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each of them_)

None.

 8. __Is it backport from main branch?__ (_If yes, please add backport PR # and commits #_)

No.

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-11-04 19:55 UTC, giocollina commented on server/multitenancy/tenant_resolver.ts
>    const globalTenantEnabled = config.multitenancy?.tenants.enable_global || false;
`|| false` was already in the original code. But you are right, since enable_global has a default value I think we do not need it. Will remove.

2021-11-15 23:59 UTC, hsiang9431-amzn commented
Tested on local cluster and the fix is working

However, we can only merge this after following tasks are done:
- Rebase fixes to new `main` branch
- Sign all commits with GPG signature, ref: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

2021-12-08 02:04 UTC, hsiang9431-amzn commented
Please review Dave's comment on this PR https://github.com/opensearch-project/security-dashboards-plugin/pull/867

2021-12-08 14:03 UTC, davidlago requested changes

2021-12-08 14:03 UTC, davidlago commented on public/apps/account/tenant-switch-panel.tsx
> +  const DEFAULT_READONLY_ROLES = ['kibana_read_only'];
Is this the right scope for this constant?

2021-12-08 14:03 UTC, davidlago commented on server/multitenancy/tenant_resolver.ts
> +  const DEFAULT_READONLY_ROLES = ['kibana_read_only'];
here is the same constant defined again. is there a common scope for this constant that could be referenced in these two files?

2022-02-12 18:03 UTC, davidlago commented
Closing in favor of #868

2022-02-12 18:03 UTC, closed without merging