Added a switcher for turning off write controls for read-only users a…
opensearch-project/security-dashboards-plugin pull request #867
Opened 2021-11-30 19:26 UTC by hsiang9431-amzn

…nd tenants

Signed-off-by: David Bennett <david.bennett@eliatra.com>

##  opensearch-project/security-dashboards-plugin pull request intake form
_Please provide as much details as possible to get feedback/acceptance on your PR quickly_

 
 1. __Category:__ (_Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation_)
 Bug fix
 
 
 2. __Github Issue # or road-map entry, if available:__
https://github.com/opensearch-project/security-dashboards-plugin/issues/776

 3. __Description of changes:__

 4. __Why these changes are required?__ 

 5. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screen-shot if available_)

 6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration testing and manual testing_)
 
 
 
 7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each of them_)

 8. __Is it backport from main branch?__ (_If yes, please add backport PR # and commits #_)

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-12-01 15:07 UTC, davidlago requested changes
Have we tested this manually?

2021-12-01 15:07 UTC, davidlago commented on server/plugin.ts
> +import { ReadOnlyCapabilitiesSwitcher } from './auth/read_only_capabilities_switcher';
Why do we have a different capitalization convention for this one? it seems like every other one imported above starts with lower case

2021-12-01 15:07 UTC, davidlago commented on server/auth/read_only_capabilities_switcher.test.ts
> +    roles: ['roleA', 'kibana_read_only'],
If we extract that list of default roles to a more global context as suggested by my other comment, please modify this test file to reference those as opposed to hardcoding them here

2021-12-01 18:04 UTC, hsiang9431-amzn commented
> Have we tested this manually?

I built from the branch and spun up a local cluster, then check its behavior

2021-12-01 18:28 UTC, davidlago submitted a review, later dismissed

2021-12-01 18:38 UTC, nsri19 approved these changes

2021-12-01 18:54 UTC, davidlago submitted a review, later dismissed

2021-12-08 02:06 UTC, hsiang9431-amzn commented
Please review Dave's comments on this PR https://github.com/opensearch-project/security-dashboards-plugin/pull/867

2022-06-09 06:07 UTC, cliu123 commented
I've rebased the PR against `main` branch. 
@opensearch-project/security Please review.

2022-06-29 23:47 UTC, cliu123 commented
Closing the PR due to inactivity for now. Please feel free to re-open if needed.

2022-06-29 23:47 UTC, closed without merging